### ISSUE TITLE
Please config adb_path in workflow settings

### ISSUE THREAD

**Issue by caipivara** [zjn0505/adb-alfred#1]
Hi

I just installed it and I see `Please config adb_path in workflow settings`, what does it mean?

**Comment by zjn0505** [comment]
Hi, thank you for trying this workflow and providing feedback.

It means this workflow needs to know where `adb` is in your computer, this is the most important prerequisite for its features.

I've attached my config screenshot for 1.2.0 version.

<img width="1349" alt="screenshot_2018-12-30_22-00-39" src="https://user-images.githubusercontent.com/6925920/50548404-7af80d00-0c7e-11e9-86ed-a10c6cccd453.png">

I'm providing the following environment variables to enable this workflow to execute commands.

- `adb_path` for commands like `adb devices`, `adb -s emulator-5554 install`

- `aapt_path` for commands like `aapt dump badging chrome.apk`

- `emulator_path` for commands like `emulator -list-avds`
