### ISSUE TITLE
Scrcpy not working

### ISSUE THREAD

**Issue by Glennmen** [zjn0505/adb-alfred#29]
I recently installed this workflow. So far so good, only thing missing is scrcpy even though I have it installed and working using terminal.

**Comment by zjn0505** [comment]
Hi, thanks for the issue. Can you help to elaborate the issue a bit more?

From my understanding you can use the rest of adb workflow functions like list packages on device, but cannot start scrcpy with the connected device.

Does it show the row of "Screen Copy with scrcpy" after select the device in the workflow? If not then it might be scrcpy not correctly detected in the workflow.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/6925920/163509135-68a26fa7-a9d9-428e-b6ef-b2cc82d18f9b.png">


> /usr/local/bin/scrcpy -v

This is the command to detect scrcpy installation.

If this step is o.k. then does it failed to start a terminal to execute scrcpy commands?

When select this row in the screenshot, it shall open a terminal and run the following command

> scrcpy -s {device_serial} -m 0

**Comment by Glennmen** [comment]
Ok I see you use a fixed path for scrcpy, that is the problem.
I installed scrcpy using Homebrew so my path is different.
![CleanShot 2022-04-15 at 09 26 49@2x](https://user-images.githubusercontent.com/11406433/163539416-21806b1a-6734-452e-9785-bb9aa6e05375.png)

**Comment by zjn0505** [comment]
I also installed scrcpy with homebrew, the different should be you have a m1 chip mac.

I will try to fix it and update soon.

**Comment by zjn0505** [comment]
Please help to check https://github.com/zjn0505/adb-alfred/releases/tag/v1.13.1

**Comment by Glennmen** [comment]
> Please help to check [`v1.13.1` (release)](https://github.com/zjn0505/adb-alfred/releases/tag/v1.13.1)

Thanks for the fast fix! This version solved it.
