### ISSUE TITLE
copy current activity path to clipboard

### ISSUE THREAD

**Issue by naturs** [zjn0505/adb-alfred#3]
eg: com.demo.MainActivity

**Comment by zjn0505** [comment]
It is feasible from my view, and actually I used to experiment on it a bit.

Do you have a desired command to dump the info? I'm thinking of
`adb shell dumpsys activity activities | grep 'Hist #' | grep com.demo`

**Comment by zjn0505** [comment]
Please check [ver. 1.4](https://github.com/zjn0505/adb-alfred/releases/tag/v1.4.0), in which I added `Dump task stacks`
It uses the following command
`adb shell dumpsys activity activities | grep 'Hist \|taskAffinity='`

It presents the list of current task and back stacks
![image](https://user-images.githubusercontent.com/6925920/56711712-7cce6a80-675e-11e9-8b01-2e5d5367a30c.png)

Use `cmd` + `Dump task stacks` will only list the top application.
Use `alt` + `Dump task stacks` will only list the top stack.
Use `cmd` + `c` on highlighted item to copy the activity path to clipboard.

Please check if this is the expected result

**Comment by naturs** [comment]
Perfect, thanks, it useful for me. 

If i press enter key, can i copy the activity path to clipboard?

**Comment by zjn0505** [comment]
Yes, added copy output to clipboard in [ver. 1.4.3](https://github.com/zjn0505/adb-alfred/releases/tag/v1.4.3).
Plus a config field `config_clipboard` to toggle it.
Default value is `1`, changing it to others will disable this function.
